name: build-nightly
run-name: Automatically building nightly-version...

on:
  push:
    branches: [ dev ]

jobs:
  build:
    strategy:
      matrix:
        # need to be changed as minecraft version changed
        # java 17 for minecraft 1.20.x
        # java 21 for minecraft 1.21.x
        java: [
          21,
        ]
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'

      - name: make gradle wrapper excutable
        run: chmod +x ./gradlew

      - name: data generation
        run: ./gradlew middle-earth:runDatagenClient

      - name: build
        run: ./gradlew build

      - name: capture build mod jar
        uses: actions/upload-artifact@v4
        with:
          name: SevenStars Project Nightly
          path: build/libs/
